include:
  - project: developer-platform/platform-scaffolding/gitlab-ci-templates
    ref: v4.3.19
    file:
      - type/java/pipeline-maven.yaml
      - type/features/java-21-maven.yaml

variables:
  ORGANISATION: riag
  PROD_CLUSTER: supply
  PRODUCT: article-mdm
  APPLICATION: tgm-x2fresh
  CONTAINER: backend
  DEPLOY_CPL: 'true'

build-verify:
  extends: .build-verify
  before_script:
    - !reference [ .build-verify, "before_script" ]
    - |
      if [ "$CI_COMMIT_BRANCH" == "$DEFAULT_BRANCH" ]
      then
        export MAVEN_CLI_OPTS="$MAVEN_CLI_OPTS -Dsonar.qualitygate.wait=false"
      fi